# Generated by Django 4.2.2 on 2023-06-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_journalentry_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='title',
        ),
    ]
